### ISSUE TITLE
Service termination

### ISSUE THREAD

**Issue by JokerQyou** [JokerQyou/ethbot#9]
We are in the progress of reducing our server fee, and have decided to terminate this service. The service will be offline from August 1st. We appreciate your help during its development.

A service notification will be sent to all registered Telegram account. It will be the first and last message actively pushed by the bot. After that all stored data will be wiped before we delete the server. We won't leave any backup as well.

The Telegram bot will be deleted too, and this repository will be archived.

Thanks again for using our service.

**Comment by cxumol** [comment]
Thanks for your service.
Is there any alternative telegram bot?

**Comment by JokerQyou** [comment]
Currently I'm not aware of any Telegram bot with the same functionality. A list of alternatives would be helpful and welcomed.

This repository will be archived after September 1st.

**Comment by JokerQyou** [comment]
I've simplified the user registration logic and created an open source version [here](https://github.com/JokerQyou/telepush.py). It's still in development but it should work. I haven't got much time for it, but hey, anyone interested can host their own instance. Also you could file a bug or share some suggestions.
